### PR TITLE
Added SSN checksum calculation and validation.

### PR DESCRIPTION
**Pull request by Mr1BitL8r**
Hi!
The code now includes the calculation of the SSN checksum and also its validation.
Hope that it helps. :)

For testing I have used the following code:

```
// TESTs
let ssnToCalculateChecksumForAsString : string;
let assumedValidity : boolean;

ssnToCalculateChecksumForAsString = "811228-987";
assumedValidity = false;
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "811228-9874";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "811228:9874";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "12811228-987";
assumedValidity = false;
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "12811228-9874";
assumedValidity = false;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "1981-12-28:9874";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "1981-12-28-9874";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "1981-12-28-9870";
assumedValidity = false;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "19811228:9874";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "12811228-9870";
assumedValidity = false;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "670919-953";
assumedValidity = false;
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "670919-9530";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "670919-9531";
assumedValidity = false;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "011-23-4567";
assumedValidity = false;
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "011234567";
assumedValidity = false;
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "1990-11-21:1233";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "199011211233";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "9011211233";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "90-11-21:1233";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "00-11-21:1232";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
console.log("");
ssnToCalculateChecksumForAsString = "2000-11-21:1232";
assumedValidity = true;
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is " + ssnCalculateChecksum(ssnToCalculateChecksumForAsString.substring(0, ssnToCalculateChecksumForAsString.length-1)));
console.log("Checksum for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsChecksumValid(ssnToCalculateChecksumForAsString));
console.log("SSN for " + ssnToCalculateChecksumForAsString + " is valid: " + ssnIsValid(ssnToCalculateChecksumForAsString) + "/" + assumedValidity);
```

### CODE REVIEW

**Comment by PatricNox** [comment]
Hi @Mr1BitL8r. 

Thanks so much for this addition!

I'll test it thoroughly  in due time and get back to you.

**Comment by Mr1BitL8r** [comment]
Good morning,
Unfortunately I have noticed a bug.
When there is a SSN with the date 2000 or 00 at the beginning the current logic calculates the checksum wrongly.
--> PR was updated and also the comment above which describes my tests.
But I may have found another issue #7

**Comment by PatricNox** [comment]
@Mr1BitL8r  good find. 

Thanks for the report! 

@ThommyDude might have some input on this?

**Comment by Mr1BitL8r** [comment]
In the latest commit I integrated the changes for Pull Request #8 which should fix #7 in this branch as well.

**Comment by PatricNox** [comment]
No longer valid due to the overhaul work, see commit list.

**Pull request closed without merging**
